from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Protocol, Self, overload, runtime_checkable

from axon.dtype import DType


@runtime_checkable
class Array[D: DType = DType](Protocol):
  """np.ndarray / mx.array / cp.ndarray 의 공통 구조 인터페이스. `D` 는 phantom
  marker — runtime `.dtype` 은 백엔드 native, axon DType 으로의 변환은 Node 에서.
  연산자 반환은 모두 `Self` (PEP 673) — Tensor 도 같은 시그니처면 만족.
  """

  @property
  def shape(self) -> tuple[int, ...]: ...

  @property
  def ndim(self) -> int: ...

  @property
  def size(self) -> int: ...

  @property
  def dtype(self) -> Any: ...

  @property
  def T(self) -> Self: ...

  def __add__(self, other: Self | int | float) -> Self: ...
  def __sub__(self, other: Self | int | float) -> Self: ...
  def __mul__(self, other: Self | int | float) -> Self: ...
  def __truediv__(self, other: Self | int | float) -> Self: ...
  def __floordiv__(self, other: Self | int | float) -> Self: ...
  def __mod__(self, other: Self | int | float) -> Self: ...
  def __pow__(self, other: Self | int | float) -> Self: ...
  def __matmul__(self, other: Self) -> Self: ...

  def __radd__(self, other: int | float) -> Self: ...
  def __rsub__(self, other: int | float) -> Self: ...
  def __rmul__(self, other: int | float) -> Self: ...
  def __rtruediv__(self, other: int | float) -> Self: ...
  def __rfloordiv__(self, other: int | float) -> Self: ...
  def __rmod__(self, other: int | float) -> Self: ...
  def __rpow__(self, other: int | float) -> Self: ...

  def __neg__(self) -> Self: ...
  def __pos__(self) -> Self: ...
  def __abs__(self) -> Self: ...
  def __invert__(self) -> Self: ...

  def __and__(self, other: Self | int) -> Self: ...
  def __or__(self, other: Self | int) -> Self: ...
  def __xor__(self, other: Self | int) -> Self: ...
  def __rand__(self, other: int) -> Self: ...
  def __ror__(self, other: int) -> Self: ...
  def __rxor__(self, other: int) -> Self: ...

  def __iadd__(self, other: Self | int | float) -> Self: ...
  def __isub__(self, other: Self | int | float) -> Self: ...
  def __imul__(self, other: Self | int | float) -> Self: ...
  def __itruediv__(self, other: Self | int | float) -> Self: ...

  def __getitem__(self, idx: Any) -> Self: ...
  def __setitem__(self, idx: Any, value: Self | int | float) -> None: ...

  # __eq__ / __ne__ 는 object 의 -> bool 와 충돌하므로 overload.
  @overload
  def __eq__(self, other: Self | int | float) -> Self: ...
  @overload
  def __eq__(self, other: object) -> bool: ...
  def __eq__(self, other: object) -> Any: ...

  @overload
  def __ne__(self, other: Self | int | float) -> Self: ...
  @overload
  def __ne__(self, other: object) -> bool: ...
  def __ne__(self, other: object) -> Any: ...

  def __lt__(self, other: Self | int | float) -> Self: ...
  def __le__(self, other: Self | int | float) -> Self: ...
  def __gt__(self, other: Self | int | float) -> Self: ...
  def __ge__(self, other: Self | int | float) -> Self: ...

  def __len__(self) -> int: ...
  def __iter__(self) -> Iterator[Self]: ...

  def __bool__(self) -> bool: ...
  def __int__(self) -> int: ...
  def __float__(self) -> float: ...
  def __index__(self) -> int: ...

  def __array__(self, dtype: Any = None) -> Any: ...


class RandomProtocol(Protocol):
  def normal(
    self,
    shape: tuple[int, ...],
    mean: float = 0.0,
    std: float = 1.0,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def uniform(
    self,
    shape: tuple[int, ...],
    low: float = 0.0,
    high: float = 1.0,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def bernoulli(
    self,
    p: float,
    shape: tuple[int, ...],
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def seed(self, s: int) -> None: ...


class BackendProtocol(Protocol):
  """Array 가 직접 안 가지는 연산 (생성, 축소, 형상, 인덱싱) 의 백엔드 인터페이스."""

  name: str
  random: RandomProtocol

  def array(self, data: Any, dtype: type[DType] = DType.FLOAT32) -> Array: ...
  def zeros(
    self, shape: tuple[int, ...], dtype: type[DType] = DType.FLOAT32
  ) -> Array: ...
  def ones(
    self, shape: tuple[int, ...], dtype: type[DType] = DType.FLOAT32
  ) -> Array: ...
  def full(
    self,
    shape: tuple[int, ...],
    fill_value: float,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...
  def zeros_like(self, x: Array) -> Array: ...
  def ones_like(self, x: Array) -> Array: ...
  def full_like(self, x: Array, fill_value: float) -> Array: ...
  def eye(self, n: int, dtype: type[DType] = DType.FLOAT32) -> Array: ...
  def arange(
    self,
    start: float,
    stop: float | None = None,
    step: float = 1.0,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def exp(self, x: Array) -> Array: ...
  def log(self, x: Array) -> Array: ...
  def sqrt(self, x: Array) -> Array: ...
  def rsqrt(self, x: Array) -> Array: ...
  def abs(self, x: Array) -> Array: ...
  def sign(self, x: Array) -> Array: ...
  def maximum(self, a: Array, b: Array) -> Array: ...
  def minimum(self, a: Array, b: Array) -> Array: ...
  def clip(self, x: Array, a_min: float, a_max: float) -> Array: ...
  def sin(self, x: Array) -> Array: ...
  def cos(self, x: Array) -> Array: ...
  def tanh(self, x: Array) -> Array: ...
  def power(self, a: Array, b: Array | float) -> Array: ...

  def sum(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def mean(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def var(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
    ddof: int = 0,
  ) -> Array: ...
  def max(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def min(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def norm(
    self,
    x: Array,
    ord: int | float | None = None,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...

  def reshape(self, x: Array, shape: tuple[int, ...]) -> Array: ...
  def transpose(self, x: Array, axes: tuple[int, ...] | None = None) -> Array: ...
  def expand_dims(self, x: Array, axis: int) -> Array: ...
  def squeeze(self, x: Array, axis: int | tuple[int, ...] | None = None) -> Array: ...
  def broadcast_to(self, x: Array, shape: tuple[int, ...]) -> Array: ...
  def concatenate(self, arrays: list[Array], axis: int = 0) -> Array: ...
  def stack(self, arrays: list[Array], axis: int = 0) -> Array: ...
  def split(
    self,
    x: Array,
    indices_or_sections: int | list[int],
    axis: int = 0,
  ) -> list[Array]: ...
  def flip(self, x: Array, axis: int | tuple[int, ...] | None = None) -> Array: ...

  def matmul(self, a: Array, b: Array) -> Array: ...
  def einsum(self, subscripts: str, *operands: Array) -> Array: ...

  def where(self, condition: Array, x: Array, y: Array) -> Array: ...
  def take(self, x: Array, indices: Array, axis: int | None = None) -> Array: ...
  def tril(self, x: Array, k: int = 0) -> Array: ...
  def triu(self, x: Array, k: int = 0) -> Array: ...

  def sort(self, x: Array, axis: int = -1) -> Array: ...
  def argsort(self, x: Array, axis: int = -1) -> Array: ...
  def argmax(
    self, x: Array, axis: int | None = None, keepdims: bool = False
  ) -> Array: ...
  def argmin(
    self, x: Array, axis: int | None = None, keepdims: bool = False
  ) -> Array: ...

  def cumsum(self, x: Array, axis: int | None = None) -> Array: ...

  def pad(
    self,
    x: Array,
    pad_width: tuple[tuple[int, int], ...],
    constant_values: float = 0.0,
  ) -> Array: ...

  def to_numpy(self, x: Array) -> Any: ...
  def from_numpy(self, x: Any) -> Array: ...
  def eval(self, *arrays: Array) -> None: ...
  def async_eval(self, *arrays: Array) -> None: ...
