from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Protocol, Self, overload, runtime_checkable

from axon.dtype import DType


@runtime_checkable
class Array[D: DType = DType](Protocol):
  """백엔드 array 객체의 공통 구조 인터페이스 (np.ndarray, mx.array, cp.ndarray).

  ## 제네릭 `D`
  axon `DType` 의 **phantom marker** — `Tensor[D: DType]` 와 일관성 유지용.
  실제 runtime `.dtype` 은 백엔드 native (`np.dtype` / `mx.Dtype` / `cp.dtype`) 이라
  `dtype: Any` 로 노출하고, axon DType 으로의 변환은 Tensor 레벨에서
  `from_backend_dtype` 가 담당한다.

  사용 예:
    `Array[DType.FLOAT32]` — fp32 배열을 의도적으로 표시 (Linear.W 등)
    `Array` (=`Array[DType]`) — dtype 미상의 일반 배열

  ## 연산자 반환 — `Self`
  모든 산술/비교 연산자는 `Self` (PEP 673) 를 반환한다. `Self` 는 호출 시점의 *구체*
  타입으로 specialize 되므로:
    - `np.ndarray + np.ndarray → np.ndarray`  (Self = np.ndarray)
    - `Tensor + Tensor → Tensor`              (Self = Tensor — autograd 그래프 노드)
  한 Protocol 로 *raw array* 와 *autograd Tensor* 둘 다 구조적으로 만족한다.
  `Tensor` 는 명시적 상속 없이 같은 시그니처만 가지면 됨.

  numpy.typing.NDArray 와 이름 충돌을 피하기 위해 `Array` 로 명명한다.
  """

  # --- 속성 ---
  @property
  def shape(self) -> tuple[int, ...]: ...

  @property
  def ndim(self) -> int: ...

  @property
  def size(self) -> int: ...

  @property
  def dtype(self) -> Any: ...

  @property
  def T(self) -> Self: ...

  # --- 산술 (좌측 self) ---
  # bool ⊂ int (Python 정적 타입) — 의도적으로 union 에 포함 안 함.
  def __add__(self, other: Self | int | float) -> Self: ...
  def __sub__(self, other: Self | int | float) -> Self: ...
  def __mul__(self, other: Self | int | float) -> Self: ...
  def __truediv__(self, other: Self | int | float) -> Self: ...
  def __floordiv__(self, other: Self | int | float) -> Self: ...
  def __mod__(self, other: Self | int | float) -> Self: ...
  def __pow__(self, other: Self | int | float) -> Self: ...
  def __matmul__(self, other: Self) -> Self: ...

  # --- 산술 (우측 self) — 스칼라가 left 인 경우만 ---
  def __radd__(self, other: int | float) -> Self: ...
  def __rsub__(self, other: int | float) -> Self: ...
  def __rmul__(self, other: int | float) -> Self: ...
  def __rtruediv__(self, other: int | float) -> Self: ...
  def __rfloordiv__(self, other: int | float) -> Self: ...
  def __rmod__(self, other: int | float) -> Self: ...
  def __rpow__(self, other: int | float) -> Self: ...

  # --- 단항 ---
  def __neg__(self) -> Self: ...
  def __pos__(self) -> Self: ...
  def __abs__(self) -> Self: ...
  def __invert__(self) -> Self: ...  # bool array NOT (~mask)

  # --- 비트 연산 (bool/int array — attention/padding mask 결합용) ---
  def __and__(self, other: Self | int) -> Self: ...
  def __or__(self, other: Self | int) -> Self: ...
  def __xor__(self, other: Self | int) -> Self: ...
  def __rand__(self, other: int) -> Self: ...
  def __ror__(self, other: int) -> Self: ...
  def __rxor__(self, other: int) -> Self: ...

  # --- In-place (재할당으로 시뮬레이션) ---
  def __iadd__(self, other: Self | int | float) -> Self: ...
  def __isub__(self, other: Self | int | float) -> Self: ...
  def __imul__(self, other: Self | int | float) -> Self: ...
  def __itruediv__(self, other: Self | int | float) -> Self: ...

  # --- 인덱싱 ---
  def __getitem__(self, idx: Any) -> Self: ...
  def __setitem__(self, idx: Any, value: Self | int | float) -> None: ...

  # --- 비교 ---
  # __eq__/__ne__ 는 object 의 기본 (-> bool) 와 충돌하므로 overload:
  #   - Array/Tensor/스칼라 → Self (element-wise bool array)
  #   - 그 외 (str 등) → bool (object default)
  @overload
  def __eq__(self, other: Self | int | float) -> Self: ...
  @overload
  def __eq__(self, other: object) -> bool: ...
  def __eq__(self, other: object) -> Any: ...

  @overload
  def __ne__(self, other: Self | int | float) -> Self: ...
  @overload
  def __ne__(self, other: object) -> bool: ...
  def __ne__(self, other: object) -> Any: ...

  def __lt__(self, other: Self | int | float) -> Self: ...
  def __le__(self, other: Self | int | float) -> Self: ...
  def __gt__(self, other: Self | int | float) -> Self: ...
  def __ge__(self, other: Self | int | float) -> Self: ...

  # --- 컨테이너 / 순회 ---
  def __len__(self) -> int: ...
  def __iter__(self) -> Iterator[Self]: ...

  # --- 스칼라 변환 (0-d array 만 의미; `float(loss)` 등) ---
  def __bool__(self) -> bool: ...
  def __int__(self) -> int: ...
  def __float__(self) -> float: ...
  def __index__(self) -> int: ...

  # --- NumPy interop (np.asarray(arr) 가 자동 호출) ---
  def __array__(self, dtype: Any = None) -> Any: ...


class RandomProtocol(Protocol):
  """난수 생성 — 가중치 초기화와 Dropout 등에 사용. BackendProtocol.random 으로 접근."""

  def normal(
    self,
    shape: tuple[int, ...],
    mean: float = 0.0,
    std: float = 1.0,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def uniform(
    self,
    shape: tuple[int, ...],
    low: float = 0.0,
    high: float = 1.0,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def bernoulli(
    self,
    p: float,
    shape: tuple[int, ...],
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  def seed(self, s: int) -> None: ...


class BackendProtocol(Protocol):
  """array 를 생성·조작하는 백엔드 인스턴스의 인터페이스.

  Array 가 직접 지원하지 않는 연산(축소, 형상 변환, 인덱싱 헬퍼 등)을 담당한다.
  난수 생성은 `random` 속성으로 분리해 NumPy 의 `np.random` 패턴을 따른다.
  """

  name: str
  random: RandomProtocol

  # --- 생성 ---
  def array(self, data: Any, dtype: type[DType] = DType.FLOAT32) -> Array: ...
  def zeros(
    self, shape: tuple[int, ...], dtype: type[DType] = DType.FLOAT32
  ) -> Array: ...
  def ones(
    self, shape: tuple[int, ...], dtype: type[DType] = DType.FLOAT32
  ) -> Array: ...
  def full(
    self,
    shape: tuple[int, ...],
    fill_value: float,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...
  def zeros_like(self, x: Array) -> Array: ...
  def ones_like(self, x: Array) -> Array: ...
  def full_like(self, x: Array, fill_value: float) -> Array: ...
  def eye(self, n: int, dtype: type[DType] = DType.FLOAT32) -> Array: ...
  def arange(
    self,
    start: float,
    stop: float | None = None,
    step: float = 1.0,
    dtype: type[DType] = DType.FLOAT32,
  ) -> Array: ...

  # --- 수학 함수 ---
  def exp(self, x: Array) -> Array: ...
  def log(self, x: Array) -> Array: ...
  def sqrt(self, x: Array) -> Array: ...
  def rsqrt(self, x: Array) -> Array: ...
  def abs(self, x: Array) -> Array: ...
  def sign(self, x: Array) -> Array: ...
  def maximum(self, a: Array, b: Array) -> Array: ...
  def minimum(self, a: Array, b: Array) -> Array: ...
  def clip(self, x: Array, a_min: float, a_max: float) -> Array: ...
  def sin(self, x: Array) -> Array: ...
  def cos(self, x: Array) -> Array: ...
  def tanh(self, x: Array) -> Array: ...
  def power(self, a: Array, b: Array | float) -> Array: ...

  # --- 축소 ---
  def sum(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def mean(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def var(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
    ddof: int = 0,
  ) -> Array: ...
  def max(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def min(
    self,
    x: Array,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...
  def norm(
    self,
    x: Array,
    ord: int | float | None = None,
    axis: int | tuple[int, ...] | None = None,
    keepdims: bool = False,
  ) -> Array: ...

  # --- 형상 ---
  def reshape(self, x: Array, shape: tuple[int, ...]) -> Array: ...
  def transpose(self, x: Array, axes: tuple[int, ...] | None = None) -> Array: ...
  def expand_dims(self, x: Array, axis: int) -> Array: ...
  def squeeze(self, x: Array, axis: int | tuple[int, ...] | None = None) -> Array: ...
  def broadcast_to(self, x: Array, shape: tuple[int, ...]) -> Array: ...
  def concatenate(self, arrays: list[Array], axis: int = 0) -> Array: ...
  def stack(self, arrays: list[Array], axis: int = 0) -> Array: ...
  def split(
    self,
    x: Array,
    indices_or_sections: int | list[int],
    axis: int = 0,
  ) -> list[Array]: ...
  def flip(self, x: Array, axis: int | tuple[int, ...] | None = None) -> Array: ...

  # --- 선형대수 ---
  def matmul(self, a: Array, b: Array) -> Array: ...
  def einsum(self, subscripts: str, *operands: Array) -> Array: ...

  # --- 인덱싱 ---
  def where(self, condition: Array, x: Array, y: Array) -> Array: ...
  def take(self, x: Array, indices: Array, axis: int | None = None) -> Array: ...
  def tril(self, x: Array, k: int = 0) -> Array: ...
  def triu(self, x: Array, k: int = 0) -> Array: ...

  # --- 정렬 / argmax 류 ---
  def sort(self, x: Array, axis: int = -1) -> Array: ...
  def argsort(self, x: Array, axis: int = -1) -> Array: ...
  def argmax(
    self, x: Array, axis: int | None = None, keepdims: bool = False
  ) -> Array: ...
  def argmin(
    self, x: Array, axis: int | None = None, keepdims: bool = False
  ) -> Array: ...

  # --- 누적 ---
  def cumsum(self, x: Array, axis: int | None = None) -> Array: ...

  # --- 패딩 ---
  def pad(
    self,
    x: Array,
    pad_width: tuple[tuple[int, int], ...],
    constant_values: float = 0.0,
  ) -> Array: ...

  # --- 변환 / 평가 ---
  def to_numpy(self, x: Array) -> Any: ...
  def from_numpy(self, x: Any) -> Array: ...
  def eval(self, *arrays: Array) -> None: ...
  def async_eval(self, *arrays: Array) -> None: ...
